steps:
  - id : 'cloning repo'
    name: gcr.io/cloud-builders/git
    args:
      - clone
      - 'https://github.com/viks1102/k8s-cluster.git'
    dir: /workspace
    id: Clone Repository

  - id : 'tf init'   
    name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
        cd /workspace/k8s-cluster/nonprod/terraform
        terraform init
    id: Terraform Init
    entrypoint: sh

  - id : 'tf plan'   
    name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
        cd /workspace/k8s-cluster/nonprod/terraform
        terraform plan -out=tfplan
    id: Terraform Plan
    entrypoint: sh

  - id : 'tf apply'    
    name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
        cd /workspace/k8s-cluster/nonprod/terraform
        if [ "$BRANCH_NAME" == "main" ]; then
          echo "Branch is main, applying Terraform plan."
          terraform apply -input=false tfplan
        else
          echo "Branch is not main, skipping Terraform apply."
        fi
    id: Terraform Apply
    entrypoint: sh
options:
  logging: CLOUD_LOGGING_ONLY
