steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - 'https://github.com/viks1102/k8s-cluster.git'
    dir: /workspace
    id: Clone Repository
  - name: 'hashicorp/terraform:light'
    args:
      - '-c'
      - |
        cd /workspace/k8s-cluster/gke-module
        terraform init -reconfigure
    id: Terraform Init
    entrypoint: sh
  - name: 'hashicorp/terraform:light'
    args:
      - '-c'
      - |
        cd /workspace/k8s-cluster/gke-module
        terraform plan -out=tfplan
    id: Terraform Plan
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
        cd /workspace/k8s-cluster/gke-module
           
        if [[ "$BRANCH_NAME" == "main" ]]; then
          echo "Branch is main, proceed with terraform apply."
          terraform apply --auto-approve 
          exit 0
        else 
          echo "Branch is not main, skip terraform apply."
          exit 0
        fi
    id: tf apply
    entrypoint: sh
    
options:
  logging: CLOUD_LOGGING_ONLY