steps:
  - id : 'cloning repo'
    name: gcr.io/cloud-builders/git
    args:
      - clone
      - 'https://github.com/viks1102/k8s-cluster.git'
    dir: /workspace

  - id : 'tf init'  
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args:
      - '-c'
      - |
        cd /workspace/k8s-cluster/gke-module
        ls -la  
        terraform init

  - id : 'tf plan'  
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args:
      - '-c'
      - |
        cd /workspace/k8s-cluster/gke-module
        terraform plan

  - id : 'tf apply'  
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args:
      - '-c'
      - |
        cd /workspace/k8s-cluster/gke-module
           
        if [[ "$BRANCH_NAME" == "main" ]]; then
          echo "Branch is main, proceed with terraform apply."
          terraform apply --auto-approve 
          exit 0
        else 
          echo "Branch is not main, skip terraform apply."
          exit 0
        fi

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
